### ISSUE TITLE
Make logging optional and replaceable

### ISSUE THREAD

**Issue by gcao** [gcao/aspector#10]
Provide a default logger but make it possible to be replaced.

logger interface

#initialize context, options = {}
#level
#level=
#visible? level
#log level, *args

log levels:
error - 50
warn - 40
info - 30
debug - 20
trace - 10

**Comment by mensfeld** [comment]
can't we use a std ruby logger and its std interface? it is common to use this approach with other loggers so aspector would integrate automatically with any logger there is (like rails logger ,etc)

**Comment by gcao** [comment]
I've not looked at the standard logger before implementing this feature. What I would like to do is to be able to change log level externally. If the standard logger supports that, we can switch to use it.

I'll close this as it's done. Feel free to open a new issue to switch logger implementation
