### ISSUE TITLE
Advice logic in string

### ISSUE THREAD

**Issue by gcao** [gcao/aspector#13]
after :initialize, "@t = Test.new"
after :test, "@t.do_something"

**Comment by mensfeld** [comment]
isn't it already in the aspector?

**Comment by gcao** [comment]
It's done but I think it should probably be removed. It's an experimental feature.

**Comment by mensfeld** [comment]
@gcao yes but on the other hand its a feature that's there and removing it would break the API - someone might use it

**Comment by gcao** [comment]
If we decide to remove it, we can do it in steps and provide warnings first. Aspector is still in pre-1.0 time, even though it might be stable enough for production use. We can make API changes if it's deemed important.

That being said, it's still to be discussed whether we should remove it. Putting logic in string does not bring anything unique except that no method is created.

**Comment by mensfeld** [comment]
Yeah I agree - there's enough better ways to do stuff than to put it in a string ;)
