### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by mensfeld** [gcao/aspector#17]
Hey, is this gem being maintained? If not I would love to take it over - we use aspector extensively and we would be able to keep it alive.

**Comment by gcao** [comment]
Thank you for contacting me and I'm very glad you're using it in your project :-D

I still got time to fix small issues if any. However I don't have plan to add new feature. I'll add you to collaborators list. If you are doing a major re-haul, please do it in a branch first.

If you can share a little about how you're using aspector, I'm very interested to hear. My email is gcao99 at  gmail

**Comment by mensfeld** [comment]
Thx - will @ you in few minutes
