### ISSUE TITLE
Doesn't work with overridden methods

### ISSUE THREAD

**Issue by bolshakov** [gcao/aspector#33]
``` ruby
let(:parent_klass) { ClassBuilder.build }
let(:aspect) do
  Aspector do
    before :exec do
      values << 'do_before'
    end
  end
end

context 'applying to overridden method' do
  let(:child_klass) do
    ClassBuilder.inherit(parent_klass) do
      def exec(_param = nil)
        values << 'exec-result-child'
      end
    end
  end

  subject { child_klass.new }

  it 'should apply a given code to the method' do
    aspect.apply(parent_klass)
    subject.exec
    expect(subject.values).to eq %w( do_before exec-result-child )
  end
end
```

``` ruby
expected: ["do_before", "exec-result"]
     got: ["exec-result-child"]
```

What do you think? Is it valid to expect that applied aspect takes effect on overridden method?

**Comment by mensfeld** [comment]
No it isn't. When you override the whole method, you cannot expect aspector to work, as you "reset" basically everything and you need to reapply aspect. I'm really not sure should I classify it as a bug or a feature request. @gcao what do you think?

**Comment by bolshakov** [comment]
I'm not sure if it's good idea too. Just checking...

**Comment by gcao** [comment]
Agree with @mensfeld. This is not a bug. However it might be worth to think about what we want to do when applying an aspect to parent and child classes.

**Comment by bolshakov** [comment]
Here is the use case. I have a parent class with abstract method. This method does nothing but I'm sure it should be decorated with specific  aspect in all its subclasses.

**Comment by gcao** [comment]
@bolshakov You can probably use [Class#inherited](http://ruby-doc.org/core-2.2.0/Class.html#method-i-inherited) to achieve what you want
```ruby
class Parent
  def self.inherited(subclass)
    aspect.apply(subclass)
  end
end
```

**Comment by mensfeld** [comment]
Won't work. We've decided to deprecate this lib in favor of native ruby prepend.
