### ISSUE TITLE
Is there a way to use aspects as mixins (traits) ?

### ISSUE THREAD

**Issue by rennhak** [gcao/aspector#34]
This gem is great! 

Is there a standard way to apply aspects using Mixins? 
Normally, when I code I tend to compose objects using traits and I was wondering if this is easily done also with `aspector` or if its impossible due to the execution model?

Any thoughts?

Thank you for your time and effort!

**Comment by mensfeld** [comment]
@rennhak  can you provide an example of what do you want to achieve?

**Comment by rennhak** [comment]
@mensfeld Apologies for the delay in answering.

I was thinking of something like this, eg.

```rb
class Something
  include Aspects::Logging
  include Aspects::ExceptionHandling
  include Aspects::Caching

  def blah
     # something happens here...
  end

end
```

Maybe not only for `class` but also for `module` as well. Does this make sense?

**Comment by mensfeld** [comment]
@rennhak sorry for such a late response. I had a summer holiday ;) there is no such way. You can wrap around aspector to provide such functionalities if you wish.

**Comment by rennhak** [comment]
@mensfeld no worries, thanks for replying, appreciate your time and effort on this.

Will experiment with wrappers to see if that solve it, cheers.

**Comment by mensfeld** [comment]
@rennhak  ping us if you have problems solving this one :)

**Comment by gcao** [comment]
You won't be able to pass parameters like below
```ruby
include Aspects::Logging, { foo: ..., blubb: ... }
```

However this should work (I didn't try them but hopefully you got the idea).
```ruby
module LoggingAspectModule
  def self.included target
    LoggingAspect.apply(target, <OPTIONS GO HERE>)
  end
end

class Something
  include LoggingAspectModule
end
```

**Comment by rennhak** [comment]
Thanks, @gcao will give your approach a try and let you know how it goes.. cheers
